### ISSUE TITLE
Change the owner of this project

### ISSUE THREAD

**Issue by alirezaomidi** [IUTFOSSCon/LandingPage#3]
What is your idea about changing the owner of IUTFOSSCon Landing page to @cessa-iut and remove this organization. Since this organization has only one project and also keeping the projects of CESSA in one place is a good idea.
What do you think? @IUTFOSSCon/owners

**Comment by 733amir** [comment]
That's a good idea. Since 2 of 3 person agreed, this discussion is over. 😃
